[versions]
# Nebula
nebula = "1.0.0-SNAPSHOT"

# Kotlin
kotlin-coroutines = "1.7.1"
kotlin-serialization = "1.5.1"

# Plugins
kotlin = "1.8.21"
detekt = "1.22.0"
spotless = "6.18.0"

[libraries]
# Kotlin
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }
kotlin-serialization-hocon = { module = "org.jetbrains.kotlinx:kotlinx-serialization-hocon", version.ref = "kotlin-serialization" }
kotlin-refection = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }

# Plugins
kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
detekt = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
spotless = { module = "com.diffplug.spotless:spotless-plugin-gradle", version.ref = "spotless" }
