name: Publish

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup email
        run: "git config --global user.email admin@triumphcraft.com"
      - name: Setup email
        run: "git config --global user.name Triumph"

      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          gradle-version: 7.5
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew publish
        
